# Writes ShaderCacheVersion.hpp for the shader disk cache (ShaderDiskCache.cpp), run at build time.
#
# The version is a hash over every source of the recompiler and of the AGC driver (the files listed
# in LIST_FILE, by path relative to ROOT and content) and the build's configuration (EXTRA): any
# change to either makes a new version, and the cache keeps the entries of each version apart.
# The header also lists every APS5_* switch the recompiler sources name: their values enter the
# cache key, since a switch may change the SPIR-V a variant compiles to.
#
# Inputs: ROOT, LIST_FILE (one absolute path per line), RECOMPILER_DIR, EXTRA, OUTPUT.

file(STRINGS "${LIST_FILE}" sources)
list(SORT sources)
set(manifest "${EXTRA}\n")
set(switches)
foreach(source IN LISTS sources)
    if(NOT EXISTS "${source}")
        continue()
    endif()
    file(SHA256 "${source}" digest)
    file(RELATIVE_PATH relative "${ROOT}" "${source}")
    string(APPEND manifest "${relative} ${digest}\n")
    string(FIND "${source}" "${RECOMPILER_DIR}/" inRecompiler)
    if(inRecompiler EQUAL 0 AND source MATCHES "\\.(cpp|hpp|h)$")
        file(STRINGS "${source}" lines REGEX "\"APS5_[A-Z0-9_]+\"")
        foreach(line IN LISTS lines)
            string(REGEX MATCHALL "\"APS5_[A-Z0-9_]+\"" names "${line}")
            list(APPEND switches ${names})
        endforeach()
    endif()
endforeach()
string(SHA256 version "${manifest}")
string(SUBSTRING "${version}" 0 16 version)
list(REMOVE_DUPLICATES switches)
list(SORT switches)
list(JOIN switches ",\n    " switchList)

set(content "// Generated by ShaderCacheVersion.cmake; do not edit.
#ifndef CORE_SHADER_RECOMPILER_SHADERCACHEVERSION_HPP
#define CORE_SHADER_RECOMPILER_SHADERCACHEVERSION_HPP

#include <cstdint>
#include <string_view>

namespace ShaderRecompiler::ShaderDiskCache::Generated {

// A hash of the recompiler and AGC driver sources and of the build configuration.
inline constexpr std::uint64_t SourceVersion = 0x${version}ull;

// The APS5_* switches the recompiler sources name.
inline constexpr std::string_view RecompilerSwitches[] = {
    ${switchList}
};

}

#endif
")

# Only a changed header is written, so an unrelated rebuild does not recompile its includers.
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
    if(previous STREQUAL content)
        return()
    endif()
endif()
file(WRITE "${OUTPUT}" "${content}")
